name: animated_analog_clock
description: "A customizable and animated analog clock widget for Flutter applications."

version: 0.2.1
homepage: https://github.com/MuhammadHasan-Git/animated_analog_clock
issue_tracker: https://github.com/MuhammadHasan-Git/animated_analog_clock/issues

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
