name: animated_analog_clock
description:
  "A customizable and animated analog clock widget for Flutter applications.
  This package provides a fully customizable analog clock widget that supports
  animation for smooth transitions of clock hands. Users can customize various
  aspects of the clock including size, colors, background, and more."

version: 0.0.1
homepage: https://github.com/MuhammadHasan-Git/animated_analog_clock
issue_tracker: https://github.com/MuhammadHasan-Git/animated_analog_clock/issues

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
